#!/usr/bin/env python3
"""
The CLI script to import KiCad symbols from the official repo.
"""
import logging

from csv import DictWriter
from os import listdir
from tempfile import TemporaryDirectory
from typing import Iterable
from zipfile import ZipFile

from enrich_part import enrich_part
from kicad.kicad_sym import KicadLibrary
from part import Part


def iterate_archive(zip_file: ZipFile):
    """
    Reads the provided ZipFile and extract "_sym" files.
    Yields the temporary directory path.
    """
    logger = logging.getLogger("iterate_archive")

    with TemporaryDirectory(prefix="kicad_") as tmp_dir:
        logger.info(f"Created temporary directory for KiCad files: {tmp_dir}")
        files_extracted = 0

        # https://docs.python.org/3/library/zipfile.html
        for item in zip_file.namelist():
            # kicad-symbols-master/74xx.kicad_sym
            if not item.endswith("_sym"):
                continue

            # INFO:iterate_archive: > Found archive item: "kicad-symbols-master/power.kicad_sym"
            # Connector_Generic.kicad_sym
            # Mechanical.kicad_sym
            if "power.kicad" in item or "/Connector" in item or "Mechanical" in item:
                continue

            # e.g. kicad-symbols-master/Transistor_FET.kicad_symdir/IRF6622.kicad_sym
            # logger.info(f' > Found archive item: "{item}", extracting...')
            zip_file.extract(item, tmp_dir)

            files_extracted += 1

            # DEBUG
            # if files_extracted > 750:
            #     break

            if files_extracted % 500 == 0:
                logger.info(f"Symbols found so far: {files_extracted} ...")

        logger.info(f"Extracted {files_extracted} symbol files to {tmp_dir}")

        # now, iterate over all subdirectories so that we can parse each one them separately
        for subdir in sorted(listdir(f'{tmp_dir}/kicad-symbols-master')):
            subdir = f'{tmp_dir}/kicad-symbols-master/{subdir}'
            logger.info(f"Yielding {subdir} sub-directory...")
            yield subdir


def iterate_parts(zip_file: ZipFile) -> Iterable[Part]:
    """
    Takes the KiCad repo zip file and yields parsed parts
    """
    logger = logging.getLogger("iterate_parts")

    for symbols_directory in iterate_archive(zip_file):
        library = KicadLibrary.from_dir(symbols_directory)
        logger.info(f"Symbols found in the {symbols_directory}: {len(library.symbols)}")

        # keep the order of symbols in the parts CSV and YML files
        for symbol in sorted(library.symbols, key=lambda s: s.name):
            try:
                part = Part.from_kicad_symbol(symbol)
                # try to fetch some additional data from the datasheets
                enrich_part(part)

                logger.info(f"* {part.name} ({part.description})")

                yield part
            except (AssertionError, TypeError) as ex:
                # WARNING:root:Part 1N4934 not parsed: Pinout of 1N4934 is empty
                # WARNING:root:Part ADAU1761 not parsed: '<' not supported between instances of 'str' and 'int'
                logger.warning(f"Part {symbol.name} not parsed: {str(ex)}")
                # raise ex


def main(archive_file: str):
    logging.info(f"Importing symbols from {archive_file} file ...")
    parts_count = 0

    with open("../parts/parts.csv", "wt", encoding="utf-8") as csv_file:
        csv = DictWriter(
            csv_file, fieldnames=["name", "description", "datasheet"], delimiter="\t"
        )
        csv.writeheader()

        with open("../parts/parts.yml", "wt", encoding="utf-8") as yaml_file:
            yaml_file.write("# Parts list generated by import_from_kicad.py\n")

            with ZipFile(archive_file, "r") as zip_file:
                for _, part in enumerate(iterate_parts(zip_file)):
                    # DEBUG
                    # if _ > 20:
                    #     break

                    # save the data into both CSV and YAML files
                    csv.writerow(
                        {
                            "name": part.name,
                            "description": part.description,
                            "datasheet": part.datasheet,
                        }
                    )

                    yaml_file.write("---\n")
                    yaml_file.write(part.as_yaml())

                    parts_count += 1

            yaml_file.write("...\n")

    # [main] Found 20780 parts
    logging.info(f"Found {parts_count} parts")
    print(f'::notice::Found {parts_count} parts')  # for GitHub Actions


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        # https://docs.python.org/3/library/logging.html#logrecord-attributes
        format="%(asctime)s %(levelname)-8s [%(funcName)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    # logging.basicConfig(level=logging.WARN)

    # fetched via "make fetch_kicad_symbols"
    main(archive_file="kicad-symbols-master.zip")
