#!/usr/bin/env python3
import logging

from csv import DictWriter
from tempfile import NamedTemporaryFile
from typing import Iterable
from zipfile import ZipFile

from kicad_sym import KicadLibrary
from part import Part

"""
Reads the provided ZipFile and extract "_sym" files.
Yields temporary file names with the extracted content, file by file.
"""
def iterate_archive(zip_file: ZipFile) -> Iterable[str]:
    logger = logging.getLogger('iterate_archive')

    # https://docs.python.org/3/library/zipfile.html
    for item in zip_file.namelist():
        # kicad-symbols-master/74xx.kicad_sym
        if not item.endswith('_sym'):
            continue

        # INFO:iterate_archive: > Found archive item: "kicad-symbols-master/power.kicad_sym"
        # Connector_Generic.kicad_sym
        # Mechanical.kicad_sym
        if 'power.kicad' in item or '/Connector' in item or 'Mechanical' in item:
            continue

        logger.info(f' > Found archive item: "{item}"')

        with zip_file.open(item, mode='r') as my_file:
            # e.g. /tmp/kicad_4ykd6li7_sym
            with NamedTemporaryFile(mode='wt', prefix='kicad_', suffix='_sym') as temp_file:
                with open(temp_file.name, 'wt') as temp_io:
                    for line in my_file:
                        temp_io.write(line.decode('utf-8'))

                logger.info(f' < Saved in "{temp_file.name}"')
                yield temp_file.name


"""
Takes the KiCad repo zip file and yields parsed parts
"""
def iterate_parts(zip_file: ZipFile) -> Iterable[Part]:
    for sym_file in iterate_archive(zip_file):
        library = KicadLibrary.from_file(sym_file)

        logging.info(f'Symbols found: {len(library.symbols)}')

        for symbol in library.symbols:
            try:
                part = Part.from_kicad_symbol(symbol)
                logging.info(f'* {part.name} ({part.description})')

                yield part
            except (AssertionError, TypeError) as ex:
                # WARNING:root:Part 1N4934 not parsed: Pinout of 1N4934 is empty
                # WARNING:root:Part ADAU1761 not parsed: '<' not supported between instances of 'str' and 'int'
                logging.warn(f'Part {symbol.name} not parsed: {str(ex)}')
                # raise ex


def main(archive_file: str):
    logging.info(f'Importing symbols from {archive_file} file ...')
    parts_count = 0

    with open('../parts/parts.csv', 'wt') as csv_file:
        csv = DictWriter(csv_file, fieldnames=['name', 'description', 'datasheet'], delimiter="\t")
        csv.writeheader()

        with open('../parts/parts.yml', 'wt') as yaml_file:
            yaml_file.write('# Parts list generated by import_from_kicad.py\n')

            with ZipFile(archive_file, 'r') as zip_file:
                for idx, part in enumerate(iterate_parts(zip_file)):
                    # DEBUG
                    # if idx > 20:
                    #     break

                    # save the data into both CSV and YAML files
                    csv.writerow({"name": part.name, "description": part.description, "datasheet": part.datasheet})

                    yaml_file.write('---\n')
                    yaml_file.write(part.as_yaml())

                    parts_count += 1

            yaml_file.write('...\n')

    # INFO:root:Found 20253 parts
    logging.info(f'Found {parts_count} parts')


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s %(levelname)-8s %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S'
    )
    # logging.basicConfig(level=logging.WARN)

    # fetch by
    # wget https://gitlab.com/kicad/libraries/kicad-symbols/-/archive/master/kicad-symbols-master.zip
    main(archive_file='kicad-symbols-master.zip')
