name: Test kicad-parser code

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      # Do not fail if one the tests did not pass
      fail-fast: false

      matrix:
        # Python version(s) to use when running the tests
        # https://github.com/actions/python-versions/blob/main/versions-manifest.json
        python-version:
          - "3.13"

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        cd kicad_parser/
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd kicad_parser/
        make test
